apiVersion: apps/v1
kind: Deployment
metadata:
  name: shit-chan
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shit-chan
  template:
    metadata:
      labels:
        app: shit-chan
    spec:
      volumes:
      - name: assets
        hostPath: 
          path: /home/nick/k8s/shit-chan
          type: Directory
      containers:
      - name: shit-chan-container
        image:  grimblo/shit-chan:1.0.8
        volumeMounts:
        - mountPath: /assets
          name: assets
        resources:
          requests:
            memory: "200Mi"
          limits:
            memory: "1.5Gi"
        env:
          - name: TOKEN
            valueFrom:
              secretKeyRef:
                name: discord-token
                key: token
          - name: TZ
            value: America/Los_Angeles
      imagePullSecrets:
        - name: regcred 